### ISSUE TITLE
Can't download model

### ISSUE THREAD

**Issue by FunkyPhoenix75** [M4cs/yourAI#4]
I am able to get through all the steps perfectly fine up until 
`gpt-2-simple download MODELNAME`
it says gpt-2-simple is not a recognized command.

**Comment by RozkolNFT** [comment]
The gpt_2_simple is not included in the requirements.txt so you will have to run `pip3 install gpt_2_simple` and then it will run as long the command is `gpt_2_simple download MODELNAME` ( _'s instand of -) for example `gpt_2_simple download 355M`
